name: Tests

on: [push]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Install Swiftly
        run: curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- -y

      - name: Install latest swift version
        run: swiftly install latest

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test --xunit-output test-reports.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Swift Tests # Name of the check run which will be created
          path: test-reports-*.xml # Path to test results
          reporter: swift-xunit # Format of test results
